<h2>新增資料至 table users</h2>

<?php echo $this->tag->form("signup/register"); ?>

    <div class="form-group">
        <label for="name">Name</label>
        <?php echo $this->tag->textField(["name", 'class' => 'form-control', "placeholder" => 'Name']); ?>
    </div>

    <div class="form-group">
        <label for="email">E-Mail</label>
        <?php echo $this->tag->emailField(["email", 'class' => 'form-control', "placeholder" => 'Email']); ?>
    </div>

    <div class="form-group">
        <?php echo $this->tag->submitButton(["Register", 'class' => 'form-control btn btn-primary']); ?>
    </div>

</form>

<?php echo $this->tag->linkTo(['/', 'Go back', 'class' => 'btn btn-primary']); ?>

