<h1>修改資料</h1>

<?php echo $this->flash->output() ?>

<?php echo $this->tag->form("test/update") ?>

    <div class="form-group">
        <?php echo $this->tag->hiddenField("id"); ?>
    </div>

    <div class="form-group">
        <label for="name">Name</label>
        <?php echo $this->tag->textField(["name", 'class' => 'form-control', "placeholder" => 'Name']); ?>
    </div>

    <div class="form-group">
        <label for="email">E-Mail</label>
        <?php echo $this->tag->emailField(["email", 'class' => 'form-control', "placeholder" => 'Email']); ?>
    </div>

    <div class="form-group">
        <?php echo $this->tag->submitButton(["Ubdate", 'class' => 'form-control btn btn-primary']); ?>
    </div>

</form>

<?php echo $this->tag->linkTo(['/test', 'Go back', 'class' => 'btn btn-primary']); ?>