<h1><?php echo $title; ?></h1>

<?php echo $this->flash->output() ?>

<table class="table">
    <tr>
        <th>id</th>
        <th>Name</th>
        <th>Email</th>
        <th></th>
        <th></th>
    </tr>
    <?php foreach ($Users as $User) { ?>
        <tr>
            <td><?php echo $User->id ?></td>
            <td><?php echo $User->name ?></td>
            <td><?php echo $User->email ?></td>
            <td><?php echo $this->tag->linkTo(["/test/edit/".$User->id, "編輯", "Add New User",'class' => 'btn btn-primary']); ?></td>
            <td><?php echo $this->tag->linkTo(["/test/delete/".$User->id, "刪除", "Add New User",'class' => 'btn btn-primary']); ?></td>
        </tr>
    <?php } ?>
</table>

<?php echo $this->tag->linkTo(["/test/new", "新增資料", "Add New User",'class' => 'btn btn-primary']); ?>

<?php echo $this->tag->linkTo(['/', 'Go back', 'class' => 'btn btn-primary']); ?>